using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using TollSystemServices;
using TollSystemServices.Enums;
using TollSystemServices.Services;

namespace TollSystemDriver.UI
{
    public partial class Bills : Form
    {
        private User CurrentUser;

        public Bills()
        {
            InitializeComponent();
            
        }

        public Bills(User currentUser)
        {

            InitializeComponent();

            this.CurrentUser = currentUser;

            InitializeBillsGridView();
        }

        public void InitializeBillsGridView()
        {
            var autoGeneratedBills = MockBills.GetMockBills(0);
            AddBillsToGridView(autoGeneratedBills);
            FormatGridView();
        }

        private void AddBillsToGridView(List<Bill> bills)
        {
            foreach(Bill bill in bills)
            {
                billsOverviewGridView.Rows.Add(bill.MotorwayEntryPoint, bill.MotorwayLeavingPoint, bill.DriverType,
                                         bill.RegistrationPlate, bill.VehicleType, $"£{bill.AmountToPay}");
            }
        }

        /// <summary>
        /// Format the grid view preview for user
        /// </summary>
        private void FormatGridView()
        {
            billsOverviewGridView.ReadOnly = true;
            billsOverviewGridView.DefaultCellStyle.SelectionBackColor = billsOverviewGridView.DefaultCellStyle.BackColor;
            billsOverviewGridView.DefaultCellStyle.SelectionForeColor = billsOverviewGridView.DefaultCellStyle.ForeColor;
            billsOverviewGridView.DefaultCellStyle.Font = new Font("Segoe UI", 10);
            billsOverviewGridView.DefaultCellStyle.ForeColor = Color.Black;
            billsOverviewGridView.DefaultCellStyle.SelectionBackColor = Color.GhostWhite;
            billsOverviewGridView.RowHeadersVisible = false;
            billsOverviewGridView.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;

            foreach (DataGridViewRow row in billsOverviewGridView.Rows)
            {
                billsOverviewGridView[0, row.Index].Style.Font = new Font("Segoe UI", 10, FontStyle.Bold);
            }

            foreach (DataGridViewColumn column in billsOverviewGridView.Columns)
            {
                column.SortMode = DataGridViewColumnSortMode.NotSortable;
            }

        }

        private void billsOverviewGridView_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            if(e?.ColumnIndex != billsOverviewGridView.Columns["payBills"].Index)
            {
                return;
            }

            string entryPoint = billsOverviewGridView[0, e.RowIndex].Value.ToString();
            string leavingPoint = billsOverviewGridView[1, e.RowIndex].Value.ToString();
            DriverType driverType = (DriverType)Enum.Parse(typeof(DriverType), billsOverviewGridView[2, e.RowIndex].Value.ToString());
            string regPlate = billsOverviewGridView[3, e.RowIndex].Value.ToString();
            string vehicleType = billsOverviewGridView[4, e.RowIndex].Value.ToString();
            double amountDue;
            double.TryParse(billsOverviewGridView[5, e.RowIndex].Value.ToString().Remove(0,1),out amountDue);
            List<string> parameters = new List<string> { entryPoint, leavingPoint, regPlate, vehicleType };


            Bill selectedBill = new Bill(parameters, driverType, amountDue);

            PayBill(selectedBill);
        }

        public void PayBill(Bill billToProcess)
        {
            PaymentProcessor paymentProcessor = new PaymentProcessor();
            paymentProcessor.PayBill();
        }
    }
}
